### PR TITLE
PEP 554: Fix typo in marshal example code (#1229)

### PR DESCRIPTION
**Pull request by dimitern**
CLA signed; fixes #1229.

### CODE REVIEW

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

**Comment by ericsnowcurrently** [comment]
You should make a PR against the upstream repo. :)

**Comment by dimitern** [comment]
@ericsnowcurrently Should I merge it then? First time.. 🥇

**Comment by dimitern** [comment]
Oops, yeah - sure :)

**Comment by ericsnowcurrently** [comment]
Your PR was against your own master branch, not upstream. :)

**Pull request merged**
